// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://tfclxyrolwvzchblzzsh.supabase.co";
const SUPABASE_SERVICE_KEY = import.meta.env.VITE_SUPABASE_SERVICE_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRmY2x4eXJvbHd2emNoYmx6enNoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0Nzc4ODQ4NCwiZXhwIjoyMDYzMzY0NDg0fQ.J0U8cN2sIiGU0Snl3nYk9E05exWA09DRin_NNOiHB-I";

// Usar o service role para todas as operações
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_SERVICE_KEY);