// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tfclxyrolwvzchblzzsh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRmY2x4eXJvbHd2emNoYmx6enNoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3ODg0ODQsImV4cCI6MjA2MzM2NDQ4NH0.pwJ8N7mxHv_7eqGA60kEhuJwtPIZDOfrHuMFjyrXk3c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);